### ISSUE TITLE
Server and Client Crash

### ISSUE THREAD

**Issue by APolarBaer** [M4thG33k/LIT_194#1]
updated to the newest LiT and now i get this >w<

net.minecraftforge.fml.common.MissingModsException: Mod gemulation (Gemulation) requires [lit]
    at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:247)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:504)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:91)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:321)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
    at java.lang.Thread.run(Unknown Source)

**Comment by M4thG33k** [comment]
Which version of Gemulation are you using?

**Comment by APolarBaer** [comment]
3.0.2... has curse not approved a new one yet lol

**Comment by M4thG33k** [comment]
I was just informed that the version of LIT I had published for 1.9.4 was the source file instead of the actual (usable) mod. Were you using the 1.9.4 version?

**Comment by APolarBaer** [comment]
Yeah im not going to 1.10 just yet

**Comment by M4thG33k** [comment]
Alright. Delete the version of LIT you currently have and install the new one that was just approved. That should fix the issue. :-) If it doesn't, let me know!

**Comment by APolarBaer** [comment]
will do, thanks as usual for the fast response~

**Comment by M4thG33k** [comment]
I aim to please! (Plus I figure I should fix stuff sooner than later, especially since I won't be able to fix things as often starting in 2 weeks... :-/

**Comment by APolarBaer** [comment]
all good now server side, checking clientside

**Comment by APolarBaer** [comment]
clientside is good too. thanks @M4thG33k

**Comment by M4thG33k** [comment]
No problem! Thanks again for letting me know about issues! :-)
